API_KEY: "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"
GOOGLE_VISION_API_KEY: "C:/Users/moham/OneDrive/Desktop/Ai resume/Backend M/New folder/AI_Backend/AI_Screen/Parser/credentials/google_vision_api_key.json"
